### ISSUE TITLE
Install Script: local-config.php has my_project as DB_NAME after install.

### ISSUE THREAD

**Issue by mattwatsoncodes** [mkdo/mkdo-base#11]
**Describe the bug**
After running install.sh the DB_NAME in local-config.php is set to my_project

**To Reproduce**

1. Pull down a project for the first time
2. Run `sh install.sh`
3. Open local-config.php
4. Note that the `DB_NAME` param is `my_project`

**Expected behavior**
I expect it to be the project name

**Comment by davetgreen** [comment]
Should be resolved with latest version, but I'll test later this week in a quiet moment. 👍

**Comment by davetgreen** [comment]
@mattwatsoncodes this should be resolved now, a second quick string replacement happens after `local-config.php` gets pulled into the project.

**Comment by davetgreen** [comment]
Confirmed as resolved.
