### ISSUE TITLE
Enforce File / Update Restrictions

### ISSUE THREAD

**Issue by davetgreen** [mkdo/mkdo-base#2]
Find a way to ensure that on , the `wp-config.php` ALWAYS has these enforced:

```
define( 'DISALLOW_FILE_MODS', true );
define( 'DISALLOW_FILE_EDIT', true );
```

**Comment by davetgreen** [comment]
@gemplank your plugin does this AMIRITE?

**Comment by gemplank** [comment]
@davetgreen yeah it does

**Comment by davetgreen** [comment]
okay then @gemplank @nervewax we need to move that `mkdo-permissions` plugin into the `mu-plugins` in this repo 👍

**Comment by gemplank** [comment]
@davetgreen i'll do it this week 👍

**Comment by davetgreen** [comment]
@gemplank if you get chance could you drop your plugin into `mu-plugins` on this? Ta.

**Comment by gemplank** [comment]
@davetgreen ah yes sorry completely forgot about this!
