### ISSUE TITLE
Kapow Phase Out

### ISSUE THREAD

**Issue by davetgreen** [mkdo/mkdo-base#3]
Pending Kimb's approval, the plan to phase out "Kapow" suggestion is as follows:

- [x] Find and replace the keywords `kapow`, `my-project` and `my_project` throughout this repo and any others with `mkdo`
- [x] Remove references to "Kapow" on [makedo.net](http://makedo.net) templates: [products page](https://www.makedo.net/products/) the site footer.
  - We could keep the products page reference to the project, but de-brand as kapow.
- [x] Remove references to Kapow in [makedo.net](http://makedo.net) blog posts.
- [x] Remove / redirect [kapow.io](http://kapow.io/) to either a new dedicated page on [makedo.net](http://makedo.net), or a blog covering the phase out.
- [x] Write a blog covering the phase out, future plans etc.

**Github**
- [x] Open new repos on [github.com/mkdo](https://github.com/mkdo/) for the boilerplate, setup and core (if we're keeping this seperate)
- [x] Decide a new name for the kapow-boilerplate repo, maybe:
  - `mkdo-starter`
  - `mkdo-base` I think humanmade use this?
  - `mkdo-root`
  - `mkdo-source`
  - or just keep it `mkdo-boilerplate`?
- [x] Port any important issues and close (currently archived) [this repo](https://github.com/kapow-wp/kapow-boilerplate)
- [x] Potentially also close this [github org](https://github.com/kapow-wp), or leave it open with a note that the project has moved.

**Comment by nervewax** [comment]
I think all that's left here is to do a sweep of makedo.net

Redirecting kapow.io and closing https://github.com/kapow-wp is optional I guess?

Writing the blog is not needed I'll check that off too.
