### ISSUE TITLE
Process Change Proposal

### ISSUE THREAD

**Issue by nervewax** [mkdo/mkdo-base#33]
Here’s what i’d propose regarding the issue/pr thing. We could try this out maybe and see if we like it more or less that just using the issues:

### Closing Issues
When an issue is ready for review and a PR has been raised, close the issue. Make sure the issue is linked to the PR.
The newly raised PR should automatically appear in the “Code Review” column and the closed issue should auto-move to the “Done” column.

### Code Review
If a PR passes a code review and initial testing, the review can be marked as “Approved” and it can move into the next column.
If there are minor code changes needed, use the “Request Changes” option in the PR review.
If the PR fails entirely, convert the PR to a draft and reopen the relevant issue, which should automatically appear in the sprint backlog. Make a note on the PR or issue about what went wrong.
If the PR passes, but new features need to be introduced (not part of the current issue), convert the PR to a draft and raise a new issue, and link that issue to the PR.

### Automations
- New issues auto go in **New Items**
- New PRs go in **Code Review** col
- Closed issues go directly to current **Done** col
- Reopened issues go in the **Sprint Backlog** col
- Approved PRs go to the **Ready to Deploy** col (consider changing the name of this?)
- Requested changes PRs go to **Sprint Backlog**
- PRs that are merged and closed go to **Done** col

---

> I think like @ Kimb said - Ready to Deploy sort of implies that the code is tested and good to go, but it actually means the code is on staging and still needs Kimb / Client to look at it before it can go to live. So maybe we just call this col something like QA? With the idea that it stays here untill it’s actually on live too?

>yeah, Ready to Deploy should mean that this can be deployed whenever someone has capacity.
We need a QA or Pending Signoff or similar column.

**Comment by davetgreen** [comment]
Signed off and ready for implementation.
