### ISSUE TITLE
Theme Options

### ISSUE THREAD

**Issue by davetgreen** [mkdo/mkdo-base#5]
Found this list I made a while back, just want to check that the theme comes out of the box with all of these:

### Customizer
- [x] Phone
- [x] Email
- [x] Facebook, twitter, linkedin + other common social links
- [ ] [editor-color-palette](https://richtabor.com/gutenberg-color-palettes/)

### Topbar
- [x] Utility navigation wp menu
- [x] Chrome theme colour  (from customizer)
- [x] Phone number (from customizer)
- [x] Email (from customizer)
- [x] Social icons (from customizer)
- [x] Call link (from customizer)

### Header
- [x] SVG logo upload (also accept png/jpg)
- [x] Primary navigation wp menu
- [x] Mobile toggle (built in toggle with js and icon)
- [x] Mobile menu opener

### Sub navigation sidebar elem  (from customizer)
- [ ] Title 
- [ ] Php to list out child pages, grandchild etc
- [ ] Mobile openable

### Lower footer
- [x] Footer menu
- [x] Copy text, current year, copyright symbol, all available in shortcode form

**Comment by davetgreen** [comment]
`On Hold` as we are probably going to tackle this with a more GB approach in light of: https://make.wordpress.org/core/2018/12/08/gutenberg-phase-2/

**Comment by gemplank** [comment]
Note: I don't think we should be adding the sidebar stuff as default as its not something we have on most sites.

**Comment by davetgreen** [comment]
@davetgreen yeah this will do, let's close off and revisit later in the year.
